apiVersion: v1
kind: Service
metadata:
  name: otel-collector-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: observability-stable-ingress
spec:
  type: NodePort
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30432
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30433
      protocol: TCP
  selector:
    app.kubernetes.io/instance: otel
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
