apiVersion: v1
kind: Service
metadata:
  name: logs-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: observability-stable-ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      nodePort: 30429
      protocol: TCP
  selector:
    app: server
    app.kubernetes.io/instance: logs
    app.kubernetes.io/name: victoria-logs-single
