#!/usr/bin/env bash
# Resolves .envrc.template via 1Password and writes real values into .envrc.
# Run this once after `op signin` — the resulting .envrc needs no further op calls.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."

op inject --in-file "$ROOT/.envrc.template" --out-file "$ROOT/.envrc.resolved"

# Wrap in export statements and add derived vars
cat > "$ROOT/.envrc" << 'HEADER'
# Generated by scripts/refresh-env.sh — do not edit directly.
# Re-run that script after op signin to refresh.
HEADER

# op inject produces raw values; wrap each in export
while IFS= read -r line; do
  [[ "$line" =~ ^# ]] && continue
  [[ -z "$line" ]] && continue
  # line is like:  VARNAME=value
  echo "export $line"
done < "$ROOT/.envrc.resolved" >> "$ROOT/.envrc"

# Append derived vars that reference the resolved ones
cat >> "$ROOT/.envrc" << 'FOOTER'
export GRAFANA_URL="http://localhost:3000"
export GRAFANA_AUTH="${GRAFANA_USERNAME}:${GRAFANA_PASSWORD}"
FOOTER

rm "$ROOT/.envrc.resolved"
echo "✓ .envrc written with resolved secrets"
